### ISSUE TITLE
Exception in thread Thread-1

### ISSUE THREAD

**Issue by vwhissell** [Abdulraheem30042/Cl0neMast3r#3]
Here:

```
================================================================================
           _____ _  ___             __  __           _   ____
          / ____| |/ _ \           |  \/  |         | | |___ \
         | |    | | | | |_ __   ___| \  / | __ _ ___| |_  __) |_ __
         | |    | | | | | '_ \ / _ \ |\/| |/ _` / __| __||__ <| '__|
         | |____| | |_| | | | |  __/ |  | | (_| \__ \ |_ ___) | |
          \_____|_|\___/|_| |_|\___|_|  |_|\__,_|___/\__|____/|_|

                                        ./Abdulraheem Khaled @Abdulrah33mK
================================================================================
[A] Add a tool using URL
[F] Find a tool on GitHub
[R] Reinstall your tools
[U] Update your tools
[S] Display your tools
[D] Delete tools list
[X] Export tools to HTML
[M] Import your tools
[E] Exit
How can I help you: Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "Cl0neMast3r.py", line 256, in update
    Tool.list = [Tool(tool.strip(), True) for tool in resource]
  File "Cl0neMast3r.py", line 34, in __init__
    self.lastUpdate = self.lastUpdate()
  File "Cl0neMast3r.py", line 42, in lastUpdate
    return self.strpTime(str(s.find("relative-time")['datetime'].replace("T", " ")[:-1]))
TypeError: 'NoneType' object has no attribute '__getitem__'
```
Item is empty. Exception should be handled.

**Comment by Abdulrah33m** [comment]
Thank you for reporting this issue
Issue has been fixed please check commit [4398b9e](https://github.com/Abdulraheem30042/Cl0neMast3r/commit/bd00705f277964c55a414f4a5a1c33f897e55872)
