### ISSUE TITLE
Bug: Script crashed on emojis & Chinese characters

### ISSUE THREAD

**Issue by PhilippBehmer** [Abdulraheem30042/Cl0neMast3r#7]
Description of gitleak contains a key emoji and another one contains Chinese characters.
https://github.com/zricethezav/gitleaks
https://github.com/5alt/GitLeak

> How can I help you: f
[Finding your tool]
[1] Search using tool name
[2] Search using username
Which one you want: 1
Enter a name to search for: gitleak
I found 5 tools, How many tools do you want me to display: 1
Tool Number: 1
Tool: gitleak
Author: 5alt
URL: https://github.com/5alt/gitleak
Availability: Available
Traceback (most recent call last):
  File "Cl0neMast3r.py", line 334, in <module>
    Tool.find(raw_input('Enter a name to search for' + red + ': ' + end), choice)
  File "Cl0neMast3r.py", line 163, in find
    Tool(foundTools[-1]).printInfo()
  File "Cl0neMast3r.py", line 92, in printInfo
    print 'Description: ' + red + self.desc + end
UnicodeEncodeError: 'ascii' codec can't encode characters in position 28-31: ordinal not in range(128)

>

**Comment by Abdulrah33m** [comment]
Okey, can you please tell me which operating system is used!
Because I have tested it and it works fine, check it [here](https://i.imgur.com/EEwv7Hj.jpg)

**Comment by PhilippBehmer** [comment]
I used the docker container I build (see pull request)
It uses ubuntu 16.04.
